### ISSUE TITLE
Next Episode popup not Showing

### ISSUE THREAD

**Issue by agentxan** [im85288/service.upnext#18] opened 2019-02-15 17:11 UTC
Libreelec 9
KODI 18
Upnext 1.0.0
Embycon 1.8.12

I am using embycon and upnext. After the first episode plays upnext pops up and goes to to the second episode but after the second episode it does not pop up for the third.

I added a log line to reset_addon_data() and sometimes it looks like it is being called after embycon sends the next episode data.

[kodi2.zip](https://github.com/im85288/service.upnext/files/2870083/kodi2.zip)

**Comment by angelblue05** [comment] 2019-06-20 01:24
This should be resolved with up next version 1.0.1

**Comment by agentxan** [comment] 2019-06-20 02:32
I have been using the latest from github and the problem looks to be fixed.

**Closed** 2019-07-28 13:20 UTC

**Comment by ShaVerZ** [comment] 2019-12-05 17:36
The popup doesnt even appear for me, Seren and Venom. Tried all versions of Up Next, inc. v1.0.7

Hopefully a fix is in the works.....

**Comment by im85288** [comment] 2019-12-05 17:39
> The popup doesnt even appear for me, Seren and Venom. Tried all versions of Up Next, inc. v1.0.7
> 
> Hopefully a fix is in the works.....

Open a new issue and follow the wiki on how to report a bug. Without that information nobody can guess what’s causing the issue on your system.

**Comment by 123Venom** [comment] 2019-12-06 08:06
I noticed the same issue...no version after 1.0.1 displays the notification anymore.

**Comment by ShaVerZ** [comment] 2019-12-09 09:56
Thanks for your reply, I'll report the issue today.
I didnt report an issue previously because I was told (Reddit) that you are aware of the issues and a fix was in the works.....

**Comment by 123Venom** [comment] 2019-12-09 17:34
> 
> 
> Thanks for your reply, I'll report the issue today.
> I didnt report an issue previously because I was told (Reddit) that you are aware of the issues and a fix was in the works.....

I'm not convince the issue is the addons.  Both Venom and Seren work fine with 1.0.1 but the moment you update beyond that version neither addon produces the pop up notification anymore.  Best way to tell is for me to log the data and see what's going on and I've not had a chance to yet.  I thought I read that 1.0.1 was the last version that used Addon Signals?  If so how does the communication then take place?  Is an addon change required for that?

**Comment by ShaVerZ** [comment] 2019-12-09 19:44
> communication

@123Venom which version of Kodi are you using, my problems started when I updated Kodi to v18

**Comment by 123Venom** [comment] 2019-12-09 20:12
I integrated UpNext into Veom while on Leia 18.1.  I'll update UpNext to latest again and do some logging to see what's failing tonight so we can hopefully get to the bottom of this.  The combo of any version of Leia, UpNext 1.0.1, and Addon Signals 0.0.3 works fine here on win pc, and Shield.

**Comment by ShaVerZ** [comment] 2019-12-09 20:15
I'm using FireTV (gen.2), I appreciate you looking in to it. 

Seems odd that this is affecting Seren also.

Thanks 😀

**Comment by dagwieers** [comment] 2019-12-10 06:25
Can you please open a new issue for this? It doesn't help hijacking an already fixed issue that happens to have the same symptoms.

In any case if v1.0.1 is the last version that worked, the breaking change is in: https://github.com/im85288/service.upnext/issues/117#issuecomment-562530274
