### ISSUE TITLE
tvshowid as int()?

### ISSUE THREAD

**Issue by 123Venom** [im85288/service.upnext#43] opened 2019-06-06 03:49 UTC
![Capture](https://user-images.githubusercontent.com/46383815/59005582-37d13580-87ec-11e9-91e3-2723de3806a9.PNG)

Getting an error that I'm sending a str() when %d expected.  Upon review I was puzzled that tvshowid is an int().  What if we use imdb as an id source that uses "tt" in the id?  I've always set ids to strings.

**Comment by angelblue05** [comment] 2019-06-06 04:22
This query needs the int of the library id assigned to the show. I don't think you can use providers to pull content from Kodi, at least I could not find the ref in the docs.

**Comment by 123Venom** [comment] 2019-06-06 04:50
I thought I read one reason from the NextUp to UpNext transition was to remove the local VideoLibrary only requirement?

https://forum.kodi.tv/showthread.php?tid=336747

**Comment by 123Venom** [comment] 2019-06-06 04:52
first sentence says "bypassing the dependency on having to have episodes in your local kodi database." so to me if it does not have to use the local database forcing it to be int() doesn't work so well to comply with that statement.

**Comment by angelblue05** [comment] 2019-06-06 05:06
Yea that is right, it supports add-on providing up next information. But what you referenced doesn't trigger if you provide up next information. It only looks at it if there's no up next information provided when up next is ready to display (it will query the default database).

**Comment by 123Venom** [comment] 2019-06-06 05:35
well that was my best guess at what param/arg was triggering the error so I went hunting through the py's.

Trying to integrate UpNext with my won addon.  I have it partly working but some kinks to work out yet and that was one log error I saw.

**Comment by angelblue05** [comment] 2019-06-06 05:58
Use this here
https://github.com/im85288/service.upnext/wiki/Data-to-Send

I find the example a bit confusing. Here is what you want to fill and send to Up Next along with a quick description of what is expected.
```
next_info = {
    "current_episode": {
    	"episodeid": string, // Any identifier you want for the episode
    	"tvshowid": string, // Any identifier you want, as long as it is reused for episodes of the same show
    	"title": string, // episode title
    	"showtitle": string, // show title
    	"plot": string, // short plot
    	"playcount": int, // episode playcount
    	"season": string, // season number
    	"episode": string, // episode number
    	"firstaired": string, // year
    	"rating": string,
    	"art": {
    		"tvshow.poster": string, // optional
    		"tvshow.fanart": string, // optional
    		"tvshow.landscape": string, // optional
    		"tvshow.clearart": string, // optional
    		"tvshow.clearlogo": string, // optional
    		"thumb": string // optional
    	}
    },
    "next_episode": {
    	"episodeid": string, // Any identifier you want for the episode
    	"tvshowid": string, // Any identifier you want, as long as it is reused for episodes of the same show
    	"title": string, // episode title
    	"showtitle": string, // show title
    	"plot": string, // short plot
    	"playcount": int, // episode playcount
    	"season": string, // season number
    	"episode": string, // episode number
    	"firstaired": string, // year
    	"rating": string,
    	"art": {
    		"tvshow.poster": string, // optional
    		"tvshow.fanart": string, // optional
    		"tvshow.landscape": string, // optional
    		"tvshow.clearart": string, // optional
    		"tvshow.clearlogo": string, // optional
    		"thumb": string // optional
    	}
    },
    "play_info": {}, // Custom dictionary your add-on provides. Up Next will it send back to initiate playback for the next episode
    "notification_time": string or int // optional
}

**Comment by 123Venom** [comment] 2019-06-06 16:26
Appreciate that and your time in this.  I'll review those.  I'm going to try switching the tvshowid to tvdb id since I have that available also.  Using ex. current_info['tvdb'] hopefully will cure the log error.  I do get the notice pop up but but it only comes up at end of the first episode I'm playing and not any subsequent ones after that.  Playlist is a whole other matter I've also been working on.

**Comment by 123Venom** [comment] 2019-06-06 16:51
well actually I forgot to add something to my ex.  int(current_info['tvdb'])

**Comment by angelblue05** [comment] 2019-06-06 21:24
You cannot do current[‘tvdb’]. You have to send exactly what I wrote. No extra keys. No missing keys either. You’ll do something like current[‘showid’] = tvdb

**Comment by 123Venom** [comment] 2019-06-07 03:59
sorry I didn't explain it well enough what I'm doing.  All values I need is contained in a dict. that I set current_info = self.meta then get the key/values I need.  I experimented with using int() and I'm still getting this error str() error I can't solve as the log does not seem to tell me what value is the problem

![Capture](https://user-images.githubusercontent.com/46383815/59080396-80edbc00-88b6-11e9-826c-a1684870a0e1.PNG)

![UpNext-error](https://user-images.githubusercontent.com/46383815/59080513-1426f180-88b7-11e9-8e67-8466edb8c4da.PNG)

**Comment by angelblue05** [comment] 2019-06-07 05:18
Change episodeid to current_info['episodeIDS']['trakt'] without the int(). Do the same for the tvshowid.

Are you certain up next is receiving your data? Seems to me it is not. Double check that.

**Comment by 123Venom** [comment] 2019-06-07 05:37
I was getting that log error with and without that int() inclusion...it wasn't in my original code I just did it as a test figuring something is passing a str when it wants an int.  Also doesn't that log error indicate it's receiving data?  sounds it to me since it saying "a number is required, not a str"...how does it know it's a str if it's not receiving anything?  I have gotten the Up Next notice to come up.  First it would only happen on the first episode then no subsequent episode.  Then I made some adjustments to the location of the AddonSignals.....to much to list...and then it reversed on me.  In other words the first episode it would not come up then it did for every subsequent episode, got figure right.  So now I'm adding a bunch of xbmc.log() stuff to I can track it's course and see what's assigned, sent and received.  I'll be back..lol

**Comment by angelblue05** [comment] 2019-06-07 05:39
No in fact the error would mean it's not receiving your add-on data since the function that contains %d are only when up next looks at the kodi database. It only does that if no data is received.

**Comment by 123Venom** [comment] 2019-06-07 07:14
Here's a case that actually worked.  You can see on line 334 I asked it to log the response...ya it says 339...lol.  I add a line here and there and forget to fix that stuff but it's for my own tracking method I do.  Now what I noted odd, and think it's a key to solving the error in my code, is that this episode i jumped to I believe 4 to start.  Seems when I do not start at episode 1 things are ok, or I'm just getting lucky to select one that my meta dict is ok cause that could be it also.  I need to log the mets dict and compare a working one with a non working and see if I can see a difference.  Honestly there should not be anything different other than an episode # and the epsiodeIDS{} I use

![Capture2](https://user-images.githubusercontent.com/46383815/59086993-70970a80-88d1-11e9-8657-39fd2376a820.PNG)

**Comment by 123Venom** [comment] 2019-06-07 07:21
You can also note on line 318 I'm logging the "next_info" I'm sending.  Ironically that line only logs on an ex. case like above that worked.  To me that means I either have a key error in the next episode or for some reason my function is not called again to create the next_info and send it.  I know a had a while loop goof that kept sending it over and over and I wrote something to deal with it so I might have made it worse...got to review that again.

NOTICE: line 318 next_info = {'play_info': {'item_id': 3380271}, 'next_episode': {'plot': u'Can Adam, Crowley and Aziraphale work together to fight the powers of Heaven and Hell and prevent the apocalypse? And what fate awaits them if they do? The story reaches its conclusion, and it might just be the end of the world.', 'tvshowid': u'359569', 'art': {'tvshow.fanart': u'http://thetvdb.com/banners/fanart/original/5c65faebc315e.jpg', 'thumb': u'http://thetvdb.com/banners/episodes/359569/7045183.jpg', 'tvshow.clearart': u'https://assets.fanart.tv/fanart/tv/359569/hdclearart/good-omens-5cf45e4486b38.png', 'tvshow.landscape': u'http://thetvdb.com/banners/fanart/original/5c65faebc315e.jpg', 'tvshow.poster': u'http://thetvdb.com/banners/posters/5c65fa5e7fa62.jpg', 'tvshow.clearlogo': u'https://assets.fanart.tv/fanart/tv/359569/hdtvlogo/good-omens-5c80278d8503f.png'}, 'title': u'The Very Last Day of the Rest of Their Lives', 'rating': u'0', 'season': u'1', 'episodeid': 3380272, 'firstaired': u'2019', 'episode': u'6', 'playcount': 0, 'showtitle': u'Good Omens'}, 'notification_time': 30, 'current_episode': {'plot': u'Aziraphale and Crowley race towards Tadfield airbase as they attempt to prevent Adam and the Four Horsemen from beginning the apocalypse. But one has been discorporated and the other is trapped in a flaming motorway. Will they get there in time?', 'tvshowid': u'359569', 'art': {'tvshow.fanart': u'http://thetvdb.com/banners/fanart/original/5c65faebc315e.jpg', 'thumb': u'http://thetvdb.com/banners/episodes/359569/7045182.jpg', 'tvshow.clearart': u'https://assets.fanart.tv/fanart/tv/359569/hdclearart/good-omens-5cf45e4486b38.png', 'tvshow.landscape': u'http://thetvdb.com/banners/fanart/original/5c65faebc315e.jpg', 'tvshow.poster': u'http://thetvdb.com/banners/posters/5c65fa5e7fa62.jpg', 'tvshow.clearlogo': u'https://assets.fanart.tv/fanart/tv/359569/hdtvlogo/good-omens-5c80278d8503f.png'}, 'title': u'The Doomsday Option', 'rating': u'0', 'season': u'1', 'episodeid': 3380271, 'firstaired': u'2019', 'episode': u'5', 'playcount': 0, 'showtitle': u'Good Omens'}}

**Comment by angelblue05** [comment] 2019-06-07 07:26
Looks ok to me. Can you follow this here and provide your Kodi log? Show me the case of it not working. Thanks
https://github.com/im85288/service.upnext/wiki/Report-a-Bug

**Comment by 123Venom** [comment] 2019-06-07 07:29
I do want to thank you for helping in this, feel so determined to get this working and think I'm close.  The more I think about it I'm not sure how one episode can work fine for the UpNext notice to come up but another episode in the same show, and season, won't work  The lists are built on the same code so the data should all be the same format.  I'm leaning towards thinking something in my code is just not sending it at times and I've heard of a few onPlaybackStarted() Kodi bugs and I think another was isPlayingVideo() that I hope is not related here.

**Comment by 123Venom** [comment] 2019-06-07 07:30
I'll send over a log with a failed case in it...might add yet a few more stuff to it to see if I can capture where it might be breaking

**Comment by angelblue05** [comment] 2019-06-07 07:31
My pleasure. A log with up next debug enable will help pinpoint where it's not working.

**Comment by 123Venom** [comment] 2019-06-07 07:37
with UpNext debug enabled I only get the line failure I showed earlier...should there be more?

**Comment by angelblue05** [comment] 2019-06-07 07:39
Yeah, there should be.
Search for "Up Next" nothing beyond that one line?

**Comment by 123Venom** [comment] 2019-06-07 07:41
could be my bad....extra info logged when system debug also on?  I running another case for the log...UpnExt debug on, my addon debug on, system debug on..could be a biggie..lol.  But I running a non case that fails

**Comment by angelblue05** [comment] 2019-06-07 07:44
Anyway, as I said previously, if it fails with that same log line, then it means there's no data by the time the dialog is supposed to show. When are you sending the stuff to up next?

**Comment by 123Venom** [comment] 2019-06-07 07:48
after playback officially begins of the episode, kind of why I was a bit worried but a few bugs that got tossed at me elsewhere as ideas.  Could be in my while loop I avoided sending the data to upnext over and over...might have foiled that a bit and need to review it again.  It's 4am here and I'm beat.  I'll try to get the log uploaded before I crash.

**Comment by 123Venom** [comment] 2019-06-07 16:17
I added traceback import to some of my exceptions to see what else I can capture and I see this.  Puzzling how it's calling my function when playback ends as my code does not seem to be the case.
It's in a while loop I have for checking watched percent that even uses "self.isPlayingVideo()" and calls a function to get out of the loop and send/receive data with AddonSignals.  I see 3 consecutive episodes of proper "next_ino" data but something in the playback is breaking this.  Feel like I'm at a stuck point in solving this

![traceback](https://user-images.githubusercontent.com/46383815/59118020-29366b80-891d-11e9-8fd0-992c396ca240.PNG)

**Comment by angelblue05** [comment] 2019-06-07 16:39
So the previous issue of %d format is gone?

I’d have to see your code, more specifically the while loop to understand what you are referring to.

**Comment by 123Venom** [comment] 2019-06-07 16:57
I diidn't see it in the log that instance but ran it again and now that error is gone...very inconsistent so I either have something really messed up or this is a bug in the isPlayingVideo()

[player.zip](https://github.com/im85288/service.upnext/files/3266896/player.zip)

**Comment by 123Venom** [comment] 2019-06-07 16:58
you're going to have a ton of questions reading that hot mess..lol

**Comment by angelblue05** [comment] 2019-06-07 17:07
No problem :) Checking it out, will get back to you shortly.

**Comment by angelblue05** [comment] 2019-06-07 17:15
This line here is what's causing issues
self.seekTime(self.media_length) You'll probably want to check if there is a file playing first.

The problem is when up next sends back the message to your add-on, it triggers as the file stops playing (this issue shouldn't happen if you trigger up next before the timer runs out).

**Comment by 123Venom** [comment] 2019-06-07 17:50
I actually got that line as a tip from the only one that has UpNext integration in their addon...hint hint.  Works for him and he gave me the logic why he does this seek to trigger the next episode to play.  I believe with it playing from a playlist the next episode will play regardless and the seek just skips to the end if one hits the "start" or "play next", whatever the button option is in the UpNext notice.

**Comment by 123Venom** [comment] 2019-06-07 17:56
for the heck of it I commented the seek out to see what would happen...log had that UpNext error again as if it did not receive data.  But the line 372 right above it in my player.py sets the "next_info" and writes it to the log and all data is there so how was it not passed on the very next line?  Puzzles the heck out of me being so inconsistent.

**Comment by im85288** [comment] 2019-06-07 17:59
There’s at least 3 addons with successful integration: https://github.com/im85288/service.upnext/wiki/Video-Addons-with-Integration I suggest looking at the code of these addons to get some inspiration. Luckily for you @angelblue05 knows her stuff and indeed is the author of one of those addons so hopefully you get there in the end

**Comment by 123Venom** [comment] 2019-06-07 18:09
appreciate all the efforts in helping me out!!!!  I'll dig through there as well.

**Comment by angelblue05** [comment] 2019-06-07 18:11
I personally don't use signals.  Can you provide your Kodi log with up next debug? You should see this line when it is succesfully received
"addon_data_received called with data"

**Comment by 123Venom** [comment] 2019-06-07 18:21
ohhh shoot my bad I promised to get that up there and plumb forgot...it was 4am and my head was nearly on my desk..lol.  Also I'm curious if I have a misconception on the kodi player...when playback of an episode ends does the __init__() run again even if playing from a playlist?  If it does not then that could be a problem as I need this marked variable reset.  That's what gets out of the while loop I explained.  If not reset to "False" then next epsiode will still be "True" and therefore won't complete the start_playback() function that sends AddonSignals

![Capture](https://user-images.githubusercontent.com/46383815/59125124-6c99d580-892f-11e9-803a-d956265c1be7.PNG)
![capture1](https://user-images.githubusercontent.com/46383815/59125160-86d3b380-892f-11e9-839a-947e37af0d1a.PNG)

**Comment by 123Venom** [comment] 2019-06-07 18:23
and for the record I've only been at python code for a little less than a year and have ALLOT to learn yet so I really do appreciate your help.

**Comment by 123Venom** [comment] 2019-06-07 18:28
It just occurred to me about my log...last time I uploaded a log I had done some manual edits because my IPTV login credentials are in there and I think a temp storage then over-wrote my edits and I couldn't solve getting around that to keep it private.  I'd rather those credentials not be out there.  Is there a means @angelblue05 I can get the log over to you that's less public?

**Comment by angelblue05** [comment] 2019-06-07 18:34
send it to my email. no problem.

__init__ is only called when the class initiates.
For example
```
class Player(xbmc.Player):
    def __init__(self):
        print("starting player class")

player = Player()
>> starting player class
```

**Comment by 123Venom** [comment] 2019-06-07 18:51
ok..I'll forward it over.  Now that variable I highlighted.  I'm seeing a problem in my own code.  Once I set that to true I'm stuck there so subsequent episodes AddonSingals will not receive anything.  The reason I wrote that was to be able to exit out of the while loop in my keepPlaybackAlive() function, otherwise I send sending over and over again.  That did cure it but I believe I introduced another problem that the variable is never reset to False....I'm going gray btw..lol

**Comment by angelblue05** [comment] 2019-06-07 19:01
Ok I'm looking at your code again. You are not using the player class correctly. But it can be fixed. The problem is that you're running everything on a single thread. The while loop prevent functions within your player class from triggering until after the while loop ends.

Your solution would be to separate your keepPlaybackAlive (and linked functions, variables) into it's own thread, separate from the player thread. Is player.py your entire code? Can I see how you initiate the player class?

**Comment by angelblue05** [comment] 2019-06-07 19:07
If you make that change, then you don't need to track if playback started or not. You'll receive the correct event via OnAVStarted, the player properties are correctly filled at that time (making your isPlayback useless and you can remove it). You should remove OnPlaybackStarted if you are using OnAVStarted. :)

**Comment by 123Venom** [comment] 2019-06-07 19:19
player.py is it.  Sent over the log via email.  I may be out resat of the day as my daughters graduation is this evening and got a busy night ahead.  You've been amazing!!!

**Comment by angelblue05** [comment] 2019-06-07 19:23
Ok I'll write you an example of what you'll want to do to resolve this since you are still new to python. Btw, is your add-on a service add-on? How do you initiate your code otherwise?

**Comment by 123Venom** [comment] 2019-06-07 19:44
not a service it's a plugin

**Comment by 123Venom** [comment] 2019-06-07 20:30
so that while loop of mine is preventing callback functions from the player?  If that's the case I didn't know that would happen.  And if that is also true means I'll have to come up with another method for that watch percent inside the loop...wonder if that could be moved to onPlaybackEnded() as a check at that point?

**Comment by angelblue05** [comment] 2019-06-07 20:50
I’ve yet to write the example. Took a break to eat. Give me a bit :)

**Comment by angelblue05** [comment] 2019-06-07 21:44
This is only a suggestion of the code that can fix your issue. I haven't checked everything functions, but what is important is the while loop not run within the player class.
.
https://gist.github.com/angelblue05/f49f1295493e3415d0c1f09533cbb204

**Comment by 123Venom** [comment] 2019-06-08 03:59
Thank you for that template and I'm already beginning a re-write to cure this while loop thing and make better use of the callback functions.  I'm curious about something though as I've also had discussions in the past with another dev on similar matters.  I got that little trick to escape the loop from him so I inquired with him on it.  He claims the player class, as I have it, does create another instance so the player class is initiated again upon plyback of the next episode and that key variable I was so concerned with "self.playback_started = False" is reset, or initiated again.  He asked me the same question you did about "How you initiate the player class", that I'm not sure I showed you or not before but here it is from a file called sources.py that gather playable sources then calls the player based on selection.

![sources](https://user-images.githubusercontent.com/46383815/59141692-b90d0180-897f-11e9-8d7f-c244f7b7faa0.PNG)

He says that will initiate another player instance on the next episode playback so it's initialized again and that variable is in fact reset to "False".  Course that was only one issue of concern but the whole "while loop" needs to be dealt with.  He wanted to test that case if the loop breaks callback functions..lol..see what I started

**Comment by angelblue05** [comment] 2019-06-08 04:45
Yes the way you are calling player will initialize it every time you call it. The loop locks player into the __init__ and that prevents other function in that class from running, I am 99% sure of that.

**Comment by 123Venom** [comment] 2019-06-08 08:54
New question because a bud of mine tested to see if keepPlaybackAlive() with loop is breaking any callback functions, because he uses similar code.  He said it's not and to test it just to add a log entry to say onPlayBackEnded() etc as I did below.  I added this log entry and played 3 episodes yet the log showed this 3 times so I'm under the impression the loop is actually not breaking the callback function.  He's saying the keepPlaybackAlive() is a non blocking thread and he's verified it.  UpNext works fine for him so perhaps it's something else breaking it for me.

![Capture](https://user-images.githubusercontent.com/46383815/59144386-46168180-89a5-11e9-9bc1-9a0d921a19d8.PNG)

Here's something he explained to me.  Is this right?

![Capture10](https://user-images.githubusercontent.com/46383815/59144771-73652e80-89a9-11e9-9f28-7285a01218d1.PNG)

**Comment by angelblue05** [comment] 2019-06-08 09:03
Hmm I recall trying that in the past myself and it wouldn’t work correctly. Maybe I was wrong about the cause, which seems to prevent more than one callback from triggering at the same time when I had the loop going. Anyway, if it works it works. :)

I’d still make the changes however since you are overlapping a lot of conditions which can be simplified up by putting those conditions closer to the top of the execution rather than part of a loop. You’d eliminate keeping track of playback, etc.

What are your upnext settings like?

**Comment by angelblue05** [comment] 2019-06-08 19:53
Did you friend run your code and said it was working fine for him? Is it a local issue?

**Comment by 123Venom** [comment] 2019-06-08 21:15
I think I may have found something that points out what the problem is but I'm just not sure I'm seeing it...maybe a thread issue it looks like to me but I'm no expert.  So what I did was added a whole ton of logging info to my player.py so I could track everything, even ALL the callback functions.  I played 3 episodes from a full season playlist.  ep1 the UpNext notice came up....ep2 it did not but played just fine.  So I then made two copies of the log data so I could put the working data along side the non working data and see what the difference is.  Working ep1 is on left, failed ep2 on right.  The "current_position" advances from the playlist fine.  I even compared all "current_info" vs. "next_info" and the data is correct.  If you spot the line that says "line 381 next_info =" the very next thing  in my code is to send that data to AddonSignals.  It's as if AddonSignals detects some reason not to send the data because it's all there for it yet the log says UpNext didn't get it the data for ep2, as seen on the right side.  I did notice some thread differences and not sure if this is what is messing up AddonSignals but I think this is where the issue is...no?

![UpNext_EP1-EP2](https://user-images.githubusercontent.com/46383815/59152393-0eddba00-8a11-11e9-88b8-4a6438041a27.PNG)

**Comment by 123Venom** [comment] 2019-06-08 21:18
and you can see in my code where I highlighted that line contains all the proper data UpNext needs and very next line seems to be the source of failure.  Let me know if you agree but in the mean time I'm going to hunt about for info on AddonSignals and what might cause it to fail.

![Capture](https://user-images.githubusercontent.com/46383815/59152405-477d9380-8a11-11e9-8d95-5f5f5106dd72.PNG)

**Comment by angelblue05** [comment] 2019-06-08 21:56
I’ll have a look in a few.

**Comment by angelblue05** [comment] 2019-06-08 22:17
I'm not fully 100% on addonsignals. Here is the alternative to using add-on signals.
```
event("upnext_data", next_info)

def event(method, data=None):
    data = data or {}
    sender = "plugin.video.venom"
    data = '\\"[\\"{0}\\"]\\"'.format(binascii.hexlify(json.dumps(data)))
    xbmc.executebuiltin('NotifyAll(%s, %s, %s)' % (sender, method, data))

class Monitor(xbmc.monitor):
    def __init__(self): #initialize the class
        super(Monitor, self).__init__()
    def onNotification(self, sender, method, data):
       # callback for upnext received here
       # sender upnextprovider.signal with your method plugin.video.venom_play_action here
       pass
```

**Comment by 123Venom** [comment] 2019-06-08 22:25
Thank you, I'll give that a try.

**Comment by 123Venom** [comment] 2019-06-09 01:15
Before tossing in the towel on AddonSignals I tried one last thing to see what I might find that's going on, cause I'm anal like that.  I enabled debug and things got rather strange.  According to what I see AddonSignals is in fact sending data for each and every episode that plays.  It looks like UpNext is throwing an error as if it waited long enough and it was not received...a timeout thing?  Now what's even weirder is that epsisode 2 & 3 have no such UpNext error but the notice never comes up.  The upNext log error is once episode 1 is playing so maybe it allow it to come up once but since the error was thown no subsequent UpNext notice?  I'm guessing but 2 & 3 looked good to me.

And the log is LOADED with this...not an error but it repeats a ton.
2019-06-08 18:48:54.996 T:8584   DEBUG: CAddonSettings[service.upnext]: loading setting definitions
2019-06-08 18:48:54.997 T:8584   DEBUG: CAddonSettings[service.upnext]: trying to load setting definitions from old format...

Here's just snips of the debug log for episodes 1 thru 3.

![UpNext-debug-ep1](https://user-images.githubusercontent.com/46383815/59153858-68a2ac00-8a32-11e9-8081-2818f47734d4.PNG)

![UpNext-debug-ep2](https://user-images.githubusercontent.com/46383815/59153859-6fc9ba00-8a32-11e9-8fc1-2e4231831377.PNG)

![UpNext-debug-ep3](https://user-images.githubusercontent.com/46383815/59153861-79532200-8a32-11e9-8954-af0dc65caa7e.PNG)

**Comment by angelblue05** [comment] 2019-06-09 01:30
You can ignore the trash logging.  However please enable up next debug. You need to enable it within the add-on settings > advacned. otherwsie nothing gets logged and no idea what up next is doing.

**Comment by 123Venom** [comment] 2019-06-09 02:24
I was just thinking of adding that sleep to see if it would stop.  Sorry but the UpNext debug, forgot I switched that back to Info.  I'll add the sleep and run another 3 episode test with debug on in UpNext.

**Comment by 123Venom** [comment] 2019-06-09 02:33
Adding one other idea to this new test.  There's no reason but be closing Dialogs at this point so I commented that out in the event that's breaking the notice from coming up.  I also see I'm not using the callback function "onPlayBackSeek()" that I want to add and clean that up also, though should not be a factor in what's going on here but the good part is I did verify that loop does not break callback functions so I know it will be good to go when for it.

![Capture](https://user-images.githubusercontent.com/46383815/59154288-fb484880-8a3c-11e9-89e7-97b4872f7bdf.PNG)

**Comment by 123Venom** [comment] 2019-06-09 03:13
Had to email that new debug log.  To much space between the values to screen capture like I did before.  Some interesting new info in there...let me know what you find.

**Comment by angelblue05** [comment] 2019-06-09 03:18
Sounds good, will check it out and keep you posted.

**Comment by 123Venom** [comment] 2019-06-09 03:24
I searched for this type of string and only found one case, which is consistent with the Up Next notice only coming up once.

NOTICE: UP NEXT Api -> log : sending data to addon to play:  {"item_id": 3378846}

**Comment by angelblue05** [comment] 2019-06-09 04:55
@123Venom Sigh I've been looking at your log and I really can't see why the addon data isn't there. Can you modify up next > resources > lib > api.py add logging to reset_addon_data(). Also within monitor,py > add to line 29 inside the tracking loop self.log(str(self.api.has_addon_data()).

Can you confirm it is not triggered after you send the up next for the second episode?

There's only two scenarios that will clear the data and it is when user stops playback and right after the up next dialog is closed. I checked your log, user stopping playback happens with the 3rd episode so it's not the issue. And the dialog closed a whole 10 seconds before the next up next data is received.

**Comment by 123Venom** [comment] 2019-06-09 05:42
sure I'll give that a whirl. I can review the log again to see if I can find where it turns false...if that's something to be found.

Sometimes I do stop that 3rd episode.  If it didn't come up after letting ep2 finish by the time there's only 10sec left of ep3 I'm pretty sure by then it's not coming up on that episode either and stop playback.

I'll report back after I make those requested changes.

**Comment by 123Venom** [comment] 2019-06-09 05:52
Just to confirm the change you want to api.py.  You just want something to write to the log so we can tell if there was a call to reset_addon_data() correct?

**Comment by angelblue05** [comment] 2019-06-09 06:06
Yes that is right to know if it's triggered.

Yes that's ok to stop the third episode since the second didn't work. Keep me posted, I'm dying to know ^^ I'm not stumped very often, this one... I honestly have no idea.

**Comment by 123Venom** [comment] 2019-06-09 06:11
new debug log sent...I'm having a peak at it now myself.

**Comment by 123Venom** [comment] 2019-06-09 06:16
shoot ya know what...I just realized I turned off all my own logging I was doing in my player.py as a test.  I've seen cases where trying to log something and it breaks so I turned it off and forgot about it for this last test so my usual logging you have been seeing is not in that latest I just emailed.  I did confirm none of my logging seems to have had any negative effect though.

**Comment by 123Venom** [comment] 2019-06-09 06:24
self.log(str(self.api.has_addon_data())

copy/paste and I didn't see the little goof so that log is junk..lol

**Comment by angelblue05** [comment] 2019-06-09 06:45
it should just return either {} or your data. Sorry I was mistaken. It's ok I will have a look at your log now. Thanks again for helping troubleshooting this thing.

**Comment by 123Venom** [comment] 2019-06-09 06:47
I should be thanking you because this is to my benefit getting this working for me.

**Comment by angelblue05** [comment] 2019-06-09 06:49
It seems your logging to up next is causing an up next error. Make sure you are not using tabs instead of spaces.
play_time = self.player.getTime()

**Comment by 123Venom** [comment] 2019-06-09 07:04
Isn't that the error I just mentioned to you from me copy/pasting the line you gave me where you were missing ")" and I didn't catch it...I used no tab.  I just pasted your string.  I have a new log version I'm about to email you where I fixed that syntax.

![Capture](https://user-images.githubusercontent.com/46383815/59156034-f3030400-8a62-11e9-890e-22ddb4b76f9d.PNG)

Unless you are talking about something else because you did say "your logging" so I'm a bit puzzled

**Comment by 123Venom** [comment] 2019-06-09 07:10
Is it me or is that log error claiming the wrong line?  syntax error was not on line 30...never touched that.  I added your

self.log(str(self.api.has_addon_data())

But there's the syntax error

![Capture](https://user-images.githubusercontent.com/46383815/59156112-f8148300-8a63-11e9-8bf4-5a9f33572e9d.PNG)

**Comment by 123Venom** [comment] 2019-06-09 07:14
the last email I sent should have that syntax error fixed, of yours..lol...and I turned back on my own logging in my player.py so searching for "current_position" will bring up the playlist items being played.  I only did 2 episodes in that because Up Next is now not coming up at all and the little tweaks I've been experimenting on does not seem to have hurt the sending of data but something about the pop up notice not being able to show has been impacted because it did come up on first episode every time.

**Comment by 123Venom** [comment] 2019-06-09 07:24
And I want to ask you about this line in the log.  Up Next still uses jasonrpc to retrieve data from what the current playlist item?  Wondering why it does that if we are sending the data.  I also notice tvshowid is -1? 

2019-06-09 02:39:52.691 T:16188  NOTICE: UP NEXT Api -> log : Got details of now playing media "{\"id\":1,\"jsonrpc\":\"2.0\",\"result\":{\"item\":{\"episode\":2,\"genre\":[\"Comedy\",\"Fantasy\",\"Mini-Series\"],\"label\":\"The Book\",\"playcount\":1,\"plotoutline\":\"\",\"season\":1,\"showtitle\":\"Good Omens\",\"tvshowid\":-1,\"type\":\"episode\"}}}"

**Comment by angelblue05** [comment] 2019-06-09 07:24
Ok so data is being reset right after the second episode is received. But why and why does it trigger several times like that? I have never seen anything like that.

Also can you confirm you are infact using the latest up next 1.0.1? Your log shows 1.0.0 which does not include any of my PR to fix these type of issues.

**Comment by angelblue05** [comment] 2019-06-09 07:27
Regarding your last reply. Up next grabs the information from the player, to grab the information from the kodi database. Since your content is external to Kodi, values are "null".

**Comment by 123Venom** [comment] 2019-06-09 07:28
lol...you're kidding? I'm on 1.0.0 right from the kodi repo with Auto Updates on so the update is not in there yet I take it?.  Let me have a look at the git branch.  That will be a trip if we just spent two days debugging this all to find out it a version issue that I don't have an update that addressed this.

**Comment by angelblue05** [comment] 2019-06-09 07:29
omg hah.

It is there, it's been there for a couple of weeks. Don't use auto update on the add-on directly. That never works right. Instead open the sideblade and do a check for updates.

**Comment by 123Venom** [comment] 2019-06-09 07:32
this is to much but least I'm laughing bout it...let me do a manual check for updates and if it updates I'll run it real quick.  That fixes it and I'm laughing for two days straight.  And I'll have to apologize to you for wasting so much of your time..brb

**Comment by im85288** [comment] 2019-06-09 07:32
Just to confirm I have not yet released it to the Kodi repo, only the Emby repo. You can find it here: https://github.com/im85288/service.upnext/releases 

I plan to submit it to the Kodi repo soon, was waiting to see if anyone at Emby complained about bugs, but so far nothing :)

**Comment by angelblue05** [comment] 2019-06-09 07:33
Oh Ian, thanks a lot for that. That would explain why I have it :)

**Comment by im85288** [comment] 2019-06-09 07:34
Haha yes Emby users are of course first priority

**Comment by 123Venom** [comment] 2019-06-09 07:37
well gonna have to download and do a zip install cause side pain..forced checked or Info check is not showing up or retrieving any update.  I know it exists because I looked on the master branch and inside the addon.xml...unreal

**Comment by 123Venom** [comment] 2019-06-09 07:49
and BOOM!!!!  Fixed, comes up every time

**Comment by angelblue05** [comment] 2019-06-09 07:51
Of course I was looking at my code already fixed and I'm like "how is this even possible"... And you would have no idea and I had no idea of the version til you started providing your full logs. Anyway, glad it's working correctly. :)

@im85288 
Seems safe to push to Kodi.

**Comment by 123Venom** [comment] 2019-06-09 07:57
yep...3 episodes in a row it came right up.  I also tested "watch now" and that little seek trick my buddy gave me works like a charm and skips right to the end to trigger the next.  Love it...and all this cause the wife is a huge Up Next fan and I told her I''ll give it a shot at getting it working in my little addon.  Things we do.  Thank you so much for your time @angelblue05 and you to @im85288 ...LOVIN IT!!!

**Comment by angelblue05** [comment] 2019-06-09 08:16
Good luck with everything. Don't forget to close this issue since it's no more.

**Comment by im85288** [comment] 2019-06-09 09:05
Great stuff guys, I’ll probably push it to the Kodi repo today. Closing this now. Cheers

**Closed by im85288** 2019-06-09 09:05 UTC

**Comment by im85288** [comment] 2019-06-09 10:41
@123Venom If you want your video addon added to the list of supported addons let me know, I’ll need the github link to point users at. If not no problem

**Comment by 123Venom** [comment] 2019-06-09 18:52
Appreciate it Ian.  I have a few more additions I'm working up for playlists and such so once complete, and satisfied it's good to go, I'll let you know.
