### ISSUE TITLE
Instant show again after play next

### ISSUE THREAD

**Issue by hawkeyexp** [im85288/service.upnext#11] opened 2018-12-22 17:35 UTC
If using play next at the end of a show new episode starts and again a play next is shown for next episode. Sems to be a problem on kodi side while triggerig more than one event - possible you can add a fix for it to ignore new events within 5 seconds etc.

**Comment by angus2064** [comment] 2019-01-06 01:16
Same thing for me ,regardless the skin used . 
I use Kodi 18RC3 on a Shield TV 2018 (test on RC4 ,same bug).

**Comment by im85288** [comment] 2019-01-14 10:45
Hmm not seeing this, let’s wait for Kodi 18 to be finalised before checking this again

**Comment by Mecool-KX** [comment] 2019-01-21 23:50
Fist of all, thank you for your great work

I have the same problem with Kodi 18 RC4

**Comment by ryanjerskine** [comment] 2019-02-11 01:05
I'm still seeing the same problem. Any details I can provide that would help get this fixed?

**Comment by im85288** [comment] 2019-02-11 08:40
Can someone upload a log? Please follow the link on the wiki of how to capture this for this add on. Thanks

**Comment by ryanjerskine** [comment] 2019-02-11 14:36
I can upload a log. I’m currently using the Google Drive plugin for all of my playback. Does that make a difference? I can switch to local playback to grab the log if I need to.

**Comment by im85288** [comment] 2019-02-11 15:00
I am not sure as I have not seen it when using either Netflix or EmbyCon as the source. Any log with it reproduced would be helpful thanks

**Comment by seanrand** [comment] 2019-02-12 09:00
I can reproduce this reliably when I click "watch next" on the "still there?" prompt after x episodes. I'll see if I can get logs.

**Comment by notoco** [comment] 2019-02-12 12:33
In the case of Netflix, this error occurs on version 0.13.21. On version 14.0b20 it is not displayed. But version 14.0b21 does not correctly indicate episodes of serials added to the library as viewed

**Comment by im85288** [comment] 2019-02-12 13:17
Personally I use the newer version 14 as it integrates better with this add on by sending a notification at the correct time to show the up next dialog (rather than waiting until 30 seconds before).

Anyway if someone can get some logs uploaded I’m sure it’ll be a simple fix

**Comment by notoco** [comment] 2019-02-12 13:27
Well, but you already have logs from two people :)
Full log - from start kodi to end.
Start episode 5... scroll to end, popup, play next and popup is show at beggining of next episode

**Comment by im85288** [comment] 2019-02-12 13:53
Whoops did not see the edited versions with logs attached. Thanks guys

**Comment by notoco** [comment] 2019-02-12 14:09
BTW - change 
`        <setting id="autoPlaySeasonTime" type="slider" label="30001" default="30" range="10,5,60" option="int" />
`
to (for example ofc)
`        <setting id="autoPlaySeasonTime" type="slider" label="30001" default="30" range="10,10,180" option="int" />
`

Why 180? Because often the payroll takes over 60 seconds ...

**Comment by im85288** [comment] 2019-02-12 14:17
Who changed it to 180? I do recall changing that at all. Originally the restriction was put in there to assure people cannot select times over 60 seconds so that the dialog counter can be shown accurately.

**Comment by Mecool-KX** [comment] 2019-02-12 15:35
Another log

https://paste.kodi.tv/dowosorowo.kodi

**Comment by notoco** [comment] 2019-02-12 15:37
Nobody has changed it - it's my suggestion to change it for example 180 :)

**Comment by Havokvalor** [comment] 2019-04-08 17:38
I am also getting this issue, I don't see anymore posts on this, was this fixed?

**Comment by im85288** [comment] 2019-04-08 17:40
It has not been fixed yet as I have been having some health issues, luckily I’m slowly getting better and will come back to it when I can.

**Comment by Havokvalor** [comment] 2019-04-12 19:03
Thank you, you are the best!

**Comment by im85288** [comment] 2019-05-04 12:09
Aiming to tackle this issue this weekend, thanks for your patience guys

**Comment by Mecool-KX** [comment] 2019-05-06 14:27
Thank you!!

**Comment by im85288** [comment] 2019-05-13 06:50
Should be fixed with the above PR

**Closed by im85288** 2019-05-13 06:50 UTC
