### ISSUE TITLE
Countdown is duplicated

### ISSUE THREAD

**Issue by ReekyMarko** [im85288/service.upnext#188] opened 2020-06-11 05:24 UTC
I have had this issue with this addon as long as it's been around, so I thought it would be best to report it.

The issue is that the up next popup has two countdowns, for example "Next episode in 05 seconds 07..."

The first countdown seems to be one second ahead. I can't take a screenshot right now but if it is absolutely necessary, I can install Kodi to my laptop to get one.

**Comment by dagwieers** [comment] 2020-06-11 10:25
Thanks for reporting. I just tested this in 2 situations:
- our Developer test pop-ups (in the Up Next settings) → no issue, but also no playback
- with TV shows (using the VRT NU add-on) → maybe a slight issue

And I think I can explain why this is (in some cases). In order to ensure that the next episode is started directly after the existing (and there is e.g. no flickering when Kodi first goes back to a listing view before the next episode is started) some add-ons are scheduling the next episode before the end of the current episode.

The time between initiating a new playback and it actually happening in Kodi depends on various factors: hardware, bandwidth, timings in code, etc.

- Can you share in which add-on you are seeing this behaviour?

- Would it be possible to try the master branch because we fixed a lot of things there as well and a release should have been done months ago :-/

There is a chance we cannot make it reasonably better, but I don't want to miss out on an opportunity to fix an actual bug either :-)

**Comment by ReekyMarko** [comment] 2020-06-11 20:32
Alright I can share my settings and test the master in the coming days. How can I install the master? Do I have to compile it somehow or are there snapshots around? Sorry, I'm a bit inexperienced with Kodi add-on development

**Comment by dagwieers** [comment] 2020-06-11 23:02
Which add-on is showing this behaviour? Or does this happen with local videos?

You can download and install this:
https://github.com/im85288/service.upnext/archive/master.zip

**Comment by dagwieers** [comment] 2020-06-12 00:04
Maybe a screenshot would be useful, because I may be misunderstanding the original report.

One way is to run `kodi-send -a TakeScreenshot` on your Kodi device/distribution, and you will find your screenshots in *~/screenshots/*.

**Comment by dagwieers** [comment] 2020-07-14 14:55
No feedback, and I think this is a duplicate of #196

**Closed by dagwieers** 2020-07-14 14:55 UTC
Labels: bug

**Comment by ReekyMarko** [comment] 2020-07-14 15:01
Sorry I totally forgot about this. But the duplicate countdown looks exactly the same as in the picture attached to #196
